/* Generated by cbindgen — do not edit manually */

#ifndef AGNO_H
#define AGNO_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct {
  unsigned char *data;
  size_t len;
  uint64_t width;
  uint64_t height;
  uint64_t page_count;
  /* Remaining fields are Rust-internal — do not access from C */
} AgnoImage;


/**
 * Result of an FFI call that returns an AgnoImage.
 * On success: image is non-null, error is null.
 * On failure: image is null, error is a malloc'd UTF-8 string.
 */
typedef struct {
  AgnoImage *image;
  uint8_t *error;
  uintptr_t error_len;
} AgnoResult;

typedef struct {
  uint8_t *data;
  uintptr_t len;
  uint16_t typ;
} ExifData;

typedef struct {
  double lat;
  double lon;
  uint8_t valid;
} GpsCoordinates;

typedef struct {
  uint8_t *data;
  uintptr_t len;
} AgnoBuffer;

AgnoResult load_image_from_path(const char *path, uintptr_t len);

#if defined(AGNO_WEBP)
void write_agno_image_to_webp(const char *path, uintptr_t len, AgnoImage *img);
#endif

AgnoResult resize_image(AgnoImage *img, uintptr_t new_width, uintptr_t new_height);

ExifData get_exif_value(const AgnoImage *img, uint16_t img_tag);

GpsCoordinates get_gps_coordinates(const AgnoImage *img);

#if defined(AGNO_JPEG)
AgnoBuffer write_agno_image_to_jpeg_buffer(const AgnoImage *img, uint8_t quality);
#endif

#if (defined(AGNO_PDF) || defined(AGNO_GIF))
/**
 * Load a specific page (or frame) from a multi-page file and return it as an AgnoImage.
 *
 * Supported formats: PDF (`%PDF-` magic), GIF (`GIF` magic), DICOM (`DICM` marker).
 *
 * `page_num` is 0-based. For PDFs, `max_width`/`max_height` of 0 uses default scale;
 * non-zero values constrain the rendered output to fit within those dimensions.
 * For GIFs and DICOM, `max_width`/`max_height` are ignored (raster, no scale-up at decode).
 */
AgnoResult load_image_page(const char *path,
                           uintptr_t len,
                           uintptr_t page_num,
                           uint32_t max_width,
                           uint32_t max_height);
#endif

void free_agno_buffer(AgnoBuffer buf);

void free_exif_data(ExifData data);

void free_agno_image(AgnoImage *img);

void free_agno_result(AgnoResult result);

void init_agno(void);

#endif  /* AGNO_H */
